# Generated by Django 5.0.6 on 2024-05-30 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(blank=None, max_length=50, unique=True)),
                ('password', models.TextField(blank=None)),
                ('create_at', models.DateTimeField(blank=None, default=datetime.datetime.now)),
                ('status', models.IntegerField(default=1)),
            ],
        ),
    ]
