# Generated by Django 5.0.6 on 2024-05-30 18:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='create_at',
            field=models.DateTimeField(blank=None, default=datetime.datetime(2024, 5, 30, 18, 56, 24, 755720)),
        ),
    ]
