# Generated by Django 5.0.6 on 2024-05-31 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0002_alter_usuario_create_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
